import { AUTH_CONSTANTS } from "./constants";

export const SESSION_ACTIVITY_REFRESH_INTERVAL_MS =
  AUTH_CONSTANTS.SESSION_ACTIVITY_REFRESH_INTERVAL_MS;

export const ACTIVE_SESSION_WINDOW_MS =
  AUTH_CONSTANTS.ACTIVE_SESSION_WINDOW_MS;